package com.secure.ai.burp.generators.payload.generators;

import burp.api.montoya.http.HttpRequestToBeSent;
import com.secure.ai.burp.generators.payload.GeneratedPayload;
import com.secure.ai.burp.generators.payload.PayloadContext;

import java.util.List;

public interface PayloadGeneratorStrategy {
    
    /**
     * Generate payloads for the given request and context
     */
    List<GeneratedPayload> generatePayloads(HttpRequestToBeSent request, PayloadContext context);
    
    /**
     * Customize a base payload for the specific context
     */
    GeneratedPayload customizePayload(String basePayload, PayloadContext context);
    
    /**
     * Get the vulnerability type this generator handles
     */
    String getVulnerabilityType();
    
    /**
     * Get the number of payloads generated by this strategy
     */
    int getGeneratedCount();
    
    /**
     * Update the strategy's learning based on payload effectiveness
     */
    void updateLearning(GeneratedPayload payload, boolean wasSuccessful, double actualEffectiveness);
    
    /**
     * Get the priority level for this vulnerability type in the given context
     */
    double getContextualPriority(PayloadContext context);
    
    /**
     * Check if this generator is applicable to the current context
     */
    boolean isApplicable(PayloadContext context);
}